# Generated by Django 5.2.3 on 2025-07-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_in_shopping_cart', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
