# Generated by Django 5.2.3 on 2025-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
